name = "a0b_stm32f2_generic_gpio_selftest"
description = "STM32F2+ Generic GPIO Driver sefltest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["a0b_stm32f2_generic_gpio_selftest.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_stm32f2_generic_gpio = "*"
gnat_arm_elf = "*"

[[pins]]
a0b_stm32f2_generic_gpio = { path='..' }
